name = "FuzzyArithmetic"
uuid = "31822d60-0862-422f-9a3d-0eb9781332f3"
authors = ["Ander Gray <ander.gray@liverpool.ac.uk>"]
version = "0.1.0"

[deps]
BivariateCopulas = "1f45d95c-a8db-40f3-940f-b9beb0518965"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
ProbabilityBoundsAnalysis = "cd73f0b2-6f06-11ea-242f-83a09de6a7cf"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
ProbabilityBoundsAnalysis = "0.2"
IntervalArithmetic = "0.18"
